<?php session_start(); ?>
<!DOCTYPE html>
<html>
	<head>
        <?php include_once "includes/header.inc"; ?>
		<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
    </head>
    <body class="home">
    	<?php include 'includes/menu.inc'; ?>

        <div id="content" align="center">
			<h2>Sorry, something went wrong and this page cannot be found</h2>
        </div>
		
		<?php include 'includes/footer.inc'; ?>
    </body>
</html>